### ISSUE TITLE
Have error if add block_isolate have error

### ISSUE THREAD

**Issue by vadimlukutin** [Maksimka101/isolate-bloc#10]
Because every version of isolate_bloc depends on provider ^4.3.1 and flutter_clean_architecture 5.0.0 depends on provider ^5.0.0, isolate_bloc is incompatible with flutter_clean_architecture 5.0.0.
And because no versions of flutter_clean_architecture match >5.0.0 <6.0.0, isolate_bloc is incompatible with flutter_clean_architecture ^5.0.0.
So, because be_logist depends on both flutter_clean_architecture ^5.0.0 and isolate_bloc ^1.0.4, version solving failed.
pub get failed (1; So, because be_logist depends on both flutter_clean_architecture ^5.0.0 and isolate_bloc ^1.0.4, version solving failed.)

**Comment by Maksimka101** [comment]
You are using flutter 2 however this package is not moved to it yet. I started this process but forget about it. I will continue switching to the flutter 2 soon

Thank you)

**Comment by Maksimka101** [comment]
Fixed in version 2.0.0
