### ISSUE TITLE
setMockMessageHandler issue

### ISSUE THREAD

**Issue by zohaib012345** [Maksimka101/isolate-bloc#17]
Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart'
![flutter issue](https://user-images.githubusercontent.com/53237092/132846676-6cfe4652-93f9-4962-930c-c23e830c2f1b.PNG)

**Comment by Maksimka101** [comment]
Hello

This package doesn't support flutter >= 2 yet. But transition already in progress and you may track it in [this](https://github.com/Maksimka101/isolate-bloc/issues/11) issue

**Comment by Maksimka101** [comment]
Fixed in version 2.0.0
