### ISSUE TITLE
Fix web support

### ISSUE THREAD

**Issue by Maksimka101** [Maksimka101/isolate-bloc#24]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/35934153/136710200-5bd8d84d-db1d-4164-ba7b-7c625ff760bb.png">

**Comment by f-person** [comment]
You want to make it run just regularly on the web or something else?

**Comment by Maksimka101** [comment]
I want it to just run and it runs however pub show that it isn't

**Comment by f-person** [comment]
Perhaps it's because `dart:isolate` is not supported on web

**Comment by Maksimka101** [comment]
Fixed in #29
