### ISSUE TITLE
Can we encode using flutter_ffmpeg inside an isolate-bloc?

### ISSUE THREAD

**Issue by aytunch** [Maksimka101/isolate-bloc#3]
Encoding with [flutter_ffmpeg](https://github.com/tanersener/flutter-ffmpeg) takes too much time and resources and generates Jank in the UI. So it would be very nice if we could run it in an isolate thread. Can we do it with the help of your library? If yes, is there a way to get progress callbacks from the thread? I want to show the user how much encoding is done. Normally flutter_ffmpeg gives this callback in its API.

Also, is there a straightforward way to allow this isolate-bloc to keep on working while the app is in the background?

**Comment by Maksimka101** [comment]
Hi.
If you are using bloc for state management you may convert your bloc to the isolate bloc. 
Or may create an isolate bloc and do your job into it.
However if you just want to convert image inside isolate you should use some libraries which helps you work with isolates or read something about them, they aren't so scary as you may think.

**Comment by Maksimka101** [comment]
Unfortunately, only native services can works in background.
